default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>


development:
  <<: *default
  database: blog_app
  username: blog_app
  password: c9e00f2ecff035a9
  url: postgresql://localhost:5432

test:
  <<: *default
  database: blog_app_test
  username: blog_app_test
  password: test
  url: postgresql://localhost:25432

production:
  <<: *default