version: '2.3'
services:
  server:
    build: 
      dockerfile: docker/build/Dockerfile
      context: ../..
    ports:
      - 3000:3000
    environment:
      - DATABASE_NAME=blog_app
      - DATABASE_USER=blog_app
      - DATABASE_PASSWORD=c9e00f2ecff035a9
      - DATABASE_URL=postgresql://db:5432
      - RAILS_LOG_TO_STDOUT=true
  
  sidekiq:
    build: 
      dockerfile: docker/build/Dockerfile
      context: ../..
    entrypoint: ./docker/build/sidekiq_entrypoint.sh
    environment:
      - DATABASE_NAME=blog_app
      - DATABASE_USER=blog_app
      - DATABASE_PASSWORD=c9e00f2ecff035a9
      - DATABASE_URL=postgresql://db:5432
      - REDIS_HOST=redis
      - RAILS_LOG_TO_STDOUT=true
  
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blog_app
      - POSTGRES_PASSWORD=c9e00f2ecff035a9
      - POSTGRES_DB=blog_app
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data:
