version: '2.3'
services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blog_app
      - POSTGRES_PASSWORD=c9e00f2ecff035a9
      - POSTGRES_DB=blog_app
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
